name: Build and Deploy Container

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: ex5travel

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR Login Server
        id: get-acr
        run: |
          ACR_LOGIN_SERVER=$(terraform -chdir=./infra output -raw acr_login_server)
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name $(terraform -chdir=./infra output -raw container_app_name) \
            --resource-group $(terraform -chdir=./infra output -raw resource_group_name) \
            --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
